### ISSUE TITLE
Pickle and shape issues

### ISSUE THREAD

**Issue by robjlyons** [danijar/dreamerv2#16]
Hi, I have been training an agent using this for a while now but today I have been getting these errors:

```
Logdir X:\Dreamer_log\logdir\ai\dreamerv2\1
Could not load episode: Object arrays cannot be loaded when allow_pickle=False
Create envs.
.\common\driver.py:64: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
Train episode has 15691 steps and return 1.4.
Traceback (most recent call last):
  File "dreamerv2/train.py", line 119, in <module>
  File ".\common\driver.py", line 56, in __call__
  File ".\common\driver.py", line 56, in <listcomp>
  File "dreamerv2/train.py", line 110, in <lambda>
  File "dreamerv2/train.py", line 102, in per_episode
  File "C:\Users\Rob\Anaconda2\envs\muzero\lib\site-packages\elements\logger.py", line 36, in video
    self.add({name: value})
  File "C:\Users\Rob\Anaconda2\envs\muzero\lib\site-packages\elements\logger.py", line 25, in add
    f"Shape {value.shape} for name '{name}' cannot be "
ValueError: Shape (15692,) for name 'train_policy' cannot be interpreted as scalar, image, or video.
```

I haven't changed anything in my system or env.

Any ideas would be great.

Thanks

**Comment by robjlyons** [comment]
Please ignore this.

it was user error on my part. Thank you
